---
# Edit this file to define the details to configure on Netbox

# netbox vars
netbox_url: 'http://192.168.254.90/'     # //https is not supported yet
netbox_token: '678bcbfccbbcb6a59069438b89b5d0f9e4a3081a'

# netbox tenants you want to create.
tenants:
<<<<<<< HEAD
  - name: Bounty
  - name: Mars
  - name: Snickers
  - name: Twix
=======
  - name: Administrator
  - name: CompanyA
  - name: CompanyB
  - name: CompanyC
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5

# netbox sites you want to create. the sites are assigned to the tenant.
# as 'tenant' needs to be id - use .(function) to search id by defined name
sites:
  - name: Paris DC1
<<<<<<< HEAD
  - name: Warsaw DC1
    asn: 65000
    time_zone: "Europe/Warsaw"
    contact_name: "NOC"
    contact_phone: "+123456789"
=======
    tenant: Administrator
  - name: Warsaw DC1
    tenant: Administrator

>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5
# netbox device-roles you want to create
device-roles: 
  - name: spine
    vm_role: false
    color: 0099ff       # blue
  - name: leaf
    vm_role: 0
    color: 00cc00       # green

# Create manufacturers
# ** Juniper ** manufacturer is created automaticly
manufacturers:
  - name: 'Arista'
  - name: 'Cisco'
    description: "Cisco Networks"

# Create platform
# ** Juniper ** Junos platform is created with a junos napalm_driver automaticly
platforms:
  - name: cisco
    napalm_driver: cisco  
    rpc_client: cisco-ios
    manufacturer: Cisco

# Create predefined device-types
# In this API request - name value not exist so we asume that first parameter would be treated as 'name' (->model)
#
# ** Juniper ** some devices are automaticly created = check netbox/juniper.py
device-types:
  - model: Nexus-9000
    manufacturer: Cisco

# prefix roles you want to create
roles: 
  - name: out_of_band_management
  - name: devices_interconnection
  - name: loopback

# prefixes you want to create. 
prefixes:
    - prefix: 10.240.40.0/24
      role: out_of_band_management
    - prefix: 10.30.20.0/23
      role: devices_interconnection
    - prefix: 10.64.0.0/24
      role: loopback

# devices you want to create. the devices are assigned to the tenant.
devices: 
    - name: Spine-20
      device_type: vqfx-10000
      device_role: spine
      serial: VM0020200000
<<<<<<< HEAD
      platform: junos-qfx
      site: Warsaw DC1
      local_context_data:
        underlay:
          bgp:
            asn: 65020
            key: mybgpkey
=======
      platform: junos
      site: Warsaw DC1
      local_context_data:
        bgp:
          asn_underlay: 65020
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5
    - name: Spine-21
      device_type: vqfx-10000
      device_role: spine
      serial: VM0021210000
<<<<<<< HEAD
      platform: junos-qfx
      site: Warsaw DC1
      local_context_data:
        underlay:
          bgp:
            asn: 65021
            key: mybgpkey
=======
      platform: junos
      site: Warsaw DC1
      local_context_data:
        bgp:
          asn_underlay: 65021
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5
    - name: Leaf-30
      device_type: vqfx-10000
      device_role: leaf
      serial: VM0030300000
<<<<<<< HEAD
      platform: junos-qfx
      site: Warsaw DC1
      local_context_data:
        underlay:
          bgp:
            asn: 65030
            key: mybgpkey
=======
      platform: junos
      site: Warsaw DC1
      local_context_data:
        bgp:
          asn_underlay: 65030
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5
    - name: Leaf-31
      device_type: vqfx-10000
      device_role: leaf
      serial: VM0031310000
<<<<<<< HEAD
      platform: junos-qfx
      site: Warsaw DC1
      local_context_data:
        underlay:
          bgp:
            asn: 65031
            key: mybgpkey
=======
      platform: junos
      site: Warsaw DC1
      local_context_data:
        bgp:
          asn_underlay: 65031
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5
    - name: Leaf-32
      device_type: vqfx-10000
      device_role: leaf
      serial: VM0032320000
<<<<<<< HEAD
      platform: junos-qfx
      site: Warsaw DC1
      local_context_data:
        underlay:
          bgp:
            asn: 65032
            key: mybgpkey
=======
      platform: junos
      site: Warsaw DC1
      local_context_data:
        bgp:
          asn_underlay: 65032
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5
    - name: Leaf-33
      device_type: vqfx-10000
      device_role: leaf
      serial: VM0033330000
<<<<<<< HEAD
      platform: junos-qfx
      site: Warsaw DC1
      local_context_data:
        underlay:
          bgp:
            asn: 65033
            key: mybgpkey
=======
      platform: junos
      site: Warsaw DC1
      local_context_data:
        bgp:
          asn_underlay: 65033
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5

# The IP addresses are assigned to the tenant.
ip-addresses:
    # out_of_band_management
    # if status == "active" (and) mgmt_only == True --> add this as active primary_ipv4 in device
<<<<<<< HEAD
    #
    - address: 10.240.40.20/22
      interface: em0@Spine-20
      mgmt_only: True
      status: "active"
    - address: 10.240.40.21/22
      interface: em0@Spine-21
      mgmt_only: True
      status: "active"
    - address: 10.240.40.30/22
      interface: em0@Leaf-30
      mgmt_only: True
      status: "active"
    - address: 10.240.40.31/22
      interface: em0@Leaf-31
      mgmt_only: True
      status: "active"
    - address: 10.240.40.32/22 
      interface: em0@Leaf-32
      mgmt_only: True
      status: "active"
    - address: 10.240.40.33/22
      interface: em0@Leaf-33
      mgmt_only: True
      status: "active"
    #
    # loopbacks (remember /32)
    #
    - address: 10.64.0.20/32
      interface: lo0.0@Spine-20
      role: "loopback"
    - address: 10.64.0.21/32
      interface: lo0.0@Spine-21
      role: loopback
    - address: 10.64.0.30/32
      interface: lo0.0@Leaf-30
      role: loopback
    - address: 10.64.0.31/32
      interface: lo0.0@Leaf-31
      role: loopback
    - address: 10.64.0.32/32
      interface: lo0.0@Leaf-32
      role: loopback
    - address: 10.64.0.33/32
      interface: lo0.0@Leaf-33
      role: loopback
    #
    # devices_interconnection
    #
    - address: 10.30.20.1/30
      interface: xe-0/0/0@Spine-20
    - address: 10.30.20.5/30
      interface: xe-0/0/1@Spine-20
    - address: 10.30.20.9/30
      interface: xe-0/0/2@Spine-20
    - address: 10.30.20.13/30
      interface: xe-0/0/3@Spine-20
    - address: 10.30.21.1/30
      interface: xe-0/0/0@Spine-21
    - address: 10.30.21.5/30
      interface: xe-0/0/1@Spine-21
    - address: 10.30.21.9/30
      interface: xe-0/0/2@Spine-21
    - address: 10.30.21.13/30
      interface: xe-0/0/3@Spine-21
    - address: 10.30.20.2/30
      interface: xe-0/0/0@Leaf-30
    - address: 10.30.21.2/30
      interface: xe-0/0/1@Leaf-30
    - address: 10.30.20.6/30
      interface: xe-0/0/0@Leaf-31
    - address: 10.30.21.6/30
      interface: xe-0/0/1@Leaf-31
    - address: 10.30.20.10/30 
      interface: xe-0/0/0@Leaf-32
    - address: 10.30.21.10/30
      interface: xe-0/0/1@Leaf-32
    - address: 10.30.20.14/30
      interface: xe-0/0/0@Leaf-33
    - address: 10.30.21.14/30
      interface: xe-0/0/1@Leaf-33
=======
    - address: 10.240.40.20/22
      device: Spine-20
      interface: em0
      mgmt_only: True
      status: "active"
    - address: 10.240.40.21/22
      device: Spine-21
      interface: em0
      mgmt_only: True
      status: "active"
    - address: 10.240.40.30/22
      device: Leaf-30
      interface: em0
      mgmt_only: True
      status: "active"
    - address: 10.240.40.31/22
      device: Leaf-31
      interface: em0
      mgmt_only: True
      status: "active"
    - address: 10.240.40.32/22
      device: Leaf-32
      interface: em0
      mgmt_only: True
      status: "active"
    - address: 10.240.40.33/22
      device: Leaf-33
      interface: em0
      mgmt_only: True
      status: "active"
    # loopbacks (remember /32)
    - address: 10.64.0.20/32
      device: Spine-20
      interface: lo0
      role: 10
    - address: 10.64.0.21/32
      device: Spine-21
      interface: lo0
      role: 10
    - address: 10.64.0.30/32
      device: Leaf-30
      interface: lo0
      role: 10
    - address: 10.64.0.31/32
      device: Leaf-31
      interface: lo0
      role: 10
    - address: 10.64.0.32/32
      device: Leaf-32
      interface: lo0
      role: 10
    - address: 10.64.0.33/32
      device: Leaf-33
      interface: lo0
      role: 10
    # devices_interconnection
    - address: 10.30.20.1/30
      device: Spine-20
      interface: xe-0/0/0
    - address: 10.30.20.5/30
      device: Spine-20
      interface: xe-0/0/1
    - address: 10.30.20.9/30
      device: Spine-20
      interface: xe-0/0/2
    - address: 10.30.20.13/30
      device: Spine-20
      interface: xe-0/0/3
    - address: 10.30.21.1/30
      device: Spine-21
      interface: xe-0/0/0
    - address: 10.30.21.5/30
      device: Spine-21
      interface: xe-0/0/1
    - address: 10.30.21.9/30
      device: Spine-21
      interface: xe-0/0/2
    - address: 10.30.21.13/30
      device: Spine-21
      interface: xe-0/0/3
    - address: 10.30.20.2/30
      device: Leaf-30
      interface: xe-0/0/0
    - address: 10.30.21.2/30
      device: Leaf-30
      interface: xe-0/0/1
    - address: 10.30.20.6/30
      device: Leaf-31
      interface: xe-0/0/0
    - address: 10.30.21.6/30
      device: Leaf-31
      interface: xe-0/0/1
    - address: 10.30.20.10/30
      device: Leaf-32
      interface: xe-0/0/0
    - address: 10.30.21.10/30
      device: Leaf-32
      interface: xe-0/0/1
    - address: 10.30.20.14/30
      device: Leaf-33
      interface: xe-0/0/0
    - address: 10.30.21.14/30
      device: Leaf-33
      interface: xe-0/0/1
>>>>>>> 7d7437bb482d12001aaa4aa5fe8e19c1023ae6d5




# define how the interfaces are connected (physical topology). 
# types: cat3, cat5, cat5e, cat6, cat6a, cat7, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, smf, smf-os1, smf-os2, aoc, power 
cables:
    - termination_a_id: xe-0/0/0@Spine-20
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/0@Leaf-30
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/1@Spine-20
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/0@Leaf-31
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/2@Spine-20
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/0@Leaf-32
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/3@Spine-20
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/0@Leaf-33
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/0@Spine-21
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/1@Leaf-30
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/1@Spine-21
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/1@Leaf-31
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/2@Spine-21
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/1@Leaf-32
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect
    - termination_a_id: xe-0/0/3@Spine-21
      termination_a_type: 'dcim.interface'
      termination_b_id: xe-0/0/1@Leaf-33
      termination_b_type: 'dcim.interface'
      type: "smf-os2"
      status: connected
      label: interconnect

