manufacturer: Juniper
model: VQFX-10000
slug: vqfx-10000
interfaces:
  - name: em0
    type: 1000base-t
    mgmt_only: true
  - name: em1
    type: 1000base-t
  - name: xe-0/0/0
    type: 10gbase-x-sfpp
  - name: xe-0/0/1
    type: 10gbase-x-sfpp
  - name: xe-0/0/2
    type: 10gbase-x-sfpp
  - name: xe-0/0/3
    type: 10gbase-x-sfpp
  - name: xe-0/0/4
    type: 10gbase-x-sfpp
  - name: xe-0/0/5
    type: 10gbase-x-sfpp
  - name: xe-0/0/6
    type: 10gbase-x-sfpp
  - name: xe-0/0/7
    type: 10gbase-x-sfpp
  - name: xe-0/0/8
    type: 10gbase-x-sfpp
  - name: xe-0/0/9
    type: 10gbase-x-sfpp
  - name: xe-0/0/10
    type: 10gbase-x-sfpp
  - name: xe-0/0/11
    type: 10gbase-x-sfpp
 